spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

groq.api.key=${GROQ_API_KEY}

workmatch.planos.ativo=false
workmatch.planos.limite-basico-mensal=2