server:
  port: ${PORT:8080}
spring:
  application:
    name: workmatch-gateway

  cloud:
    gateway:
      default-filters:
        - Retry=3
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials 

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "https://workmatch-backend-d6f9.onrender.com"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO